// types constants

export const UPDATE_THREADS = 'UPDATE_THREADS';
export const APPEND_THREAD_MESSAGES = 'APPEND_THREAD_MESSAGES';
export const PREPEND_THREAD_MESSAGES = 'PREPEND_THREAD_MESSAGES';
export const UPDATE_CACHED_THREAD_ID = 'UPDATE_CACHED_THREAD_ID';
export const UPDATE_THREAD_OFFSET = 'UPDATE_THREAD_OFFSET';
export const UPDATE_LINKED_IMPULSES = 'UPDATE_LINKED_IMPULSES';
export const UPDATE_SESSION_IMPULSES = 'UPDATE_SESSION_IMPULSES';
export const UPDATE_LINKED_SPARKS = 'UPDATE_LINKED_SPARKS';
export const UPDATE_SESSION_SPARKS = 'UPDATE_SESSION_SPARKS';
export const SET_ACTIVE_THREAD = 'SET_ACTIVE_THREAD';
export const SET_CENTER_COMPONENT = 'SET_CENTER_COMPONENT';
export const LOGIN = 'LOGIN';
export const SET_SESSION = 'SET_SESSION';
export const SET_ACTIVE_ITEMS = 'SET_ACTIVE_ITEMS';
export const ERROR_OCCURED = 'ERROR_OCCURED';
export const SET_INVALID_HASH_ERROR = 'SET_INVALID_HASH_ERROR';
